services:
  query-service:
    build:
      context: ./query-service
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    depends_on:
      rabbitmq:
            condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:8081/actuator/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    networks:
      - app-network

  booking-service:
    build:
      context: ./booking
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    deploy:
      replicas: 1
    networks:
      - app-network

  polregio-scraper:
    build:
      context: ./polregio
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    depends_on:
      rabbitmq:
            condition: service_healthy
      query-service:
            condition: service_healthy
    networks:
      - app-network

  intercity-scraper:
    build:
      context: ./intercity
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    depends_on:
      rabbitmq:
        condition: service_healthy
      query-service:
        condition: service_healthy
    networks:
      - app-network

  flixbus-scraper:
    build:
      context: ./flixbus
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    depends_on:
      rabbitmq:
        condition: service_healthy
      query-service:
        condition: service_healthy
    networks:
      - app-network


  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
    depends_on:
      - query-service
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

networks:
  app-network:
    driver: bridge