services:
  query-service:
    image: gresiu/rsww_207125_query-service
    deploy:
      replicas: 1
    depends_on:
      - rabbitmq
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:8081/actuator/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    networks:
      - rsww_207125_network

  booking-service:
    image: gresiu/rsww_207125_booking-service
    ports:
      - "20712:5005"
    deploy:
      replicas: 1
    networks:
      - rsww_207125_network
      - admin-mysql_default

  polregio-scraper:
    image: gresiu/rsww_207125_polregio-scraper
    deploy:
      replicas: 1
    depends_on:
      - rabbitmq
      - query-service
    networks:
      - rsww_207125_network

  intercity-scraper:
    image: gresiu/rsww_207125_intercity-scraper
    deploy:
      replicas: 1
    depends_on:
      - rabbitmq
      - query-service
    networks:
      - rsww_207125_network

  flixbus-scraper:
    image: gresiu/rsww_207125_flixbus-scraper
    deploy:
      replicas: 1
    depends_on:
      - rabbitmq
      - query-service
    networks:
      - rsww_207125_network

  gateway:
    image: gresiu/rsww_207125_gateway
    ports:
      - "20725:8080"
    deploy:
      replicas: 1
    depends_on:
      - query-service
    networks:
      - rsww_207125_network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "20713:5672"
      - "20714:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - rsww_207125_network

  client:
    image: gresiu/rsww_207125_client
    ports:
      - "20727:3000"

  eureka-server:
    image: gresiu/rsww_207125_eureka-server
    ports:
      - "20741:8761"
    deploy:
      replicas: 1
    networks:
      - rsww_207125_network

networks:
  rsww_207125_network:
    driver: overlay
  admin-mysql_default:
    external: true

volumes:
  rabbitmq-data:
    driver: local